src/Entity/Apmokejimas.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApmokejimasRepository")
 */
class Apmokejimas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Kiekis;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Data;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="kliento_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Kliento_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKiekis(): ?int
    {
        return $this->Kiekis;
    }

    public function setKiekis(int $Kiekis): self
    {
        $this->Kiekis = $Kiekis;

        return $this;
    }

    public function getData(): ?\DateTimeInterface
    {
        return $this->Data;
    }

    public function setData(\DateTimeInterface $Data): self
    {
        $this->Data = $Data;

        return $this;
    }

    public function getKlientoId(): ?user
    {
        return $this->Kliento_id;
    }

    public function setKlientoId(?user $Kliento_id): self
    {
        $this->Kliento_id = $Kliento_id;

        return $this;
    }
}

src/Entity/Uzsakymas.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UzsakymasRepository")
 */
class Uzsakymas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $sukurimo_data;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $pristatymo_data;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $patvirtinimo_data;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresas;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="uzsakymas")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\UzsakymoBusena", inversedBy="uzsakymas")
     */
    private $busena;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Siuntinys", cascade={"persist", "remove"})
     */
    private $siuntinys;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Atsiliepimas", mappedBy="uzsakymas", cascade={"persist", "remove"})
     */
    private $atsiliepimas;

    public function __construct()
    {
        $this->sukurimo_data = new DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSukurimoData(): ?\DateTimeInterface
    {
        return $this->sukurimo_data;
    }

    public function setSukurimoData(\DateTimeInterface $sukurimo_data): self
    {
        $this->sukurimo_data = $sukurimo_data;

        return $this;
    }

    public function getPristatymoData(): ?\DateTimeInterface
    {
        return $this->pristatymo_data;
    }

    public function setPristatymoData(\DateTimeInterface $pristatymo_data): self
    {
        $this->pristatymo_data = $pristatymo_data;

        return $this;
    }

    public function getPatvirtinimoData(): ?\DateTimeInterface
    {
        return $this->patvirtinimo_data;
    }

    public function setPatvirtinimoData(\DateTimeInterface $patvirtinimo_data): self
    {
        $this->patvirtinimo_data = $patvirtinimo_data;

        return $this;
    }

    public function getAdresas(): ?string
    {
        return $this->adresas;
    }

    public function setAdresas(string $adresas): self
    {
        $this->adresas = $adresas;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBusena(): ?UzsakymoBusena
    {
        return $this->busena;
    }

    public function setBusena(?UzsakymoBusena $busena): self
    {
        $this->busena = $busena;

        return $this;
    }

    public function getSiuntinys(): ?Siuntinys
    {
        return $this->siuntinys;
    }

    public function setSiuntinys(?Siuntinys $siuntinys): self
    {
        $this->siuntinys = $siuntinys;

        return $this;
    }

    public function getAtsiliepimas(): ?Atsiliepimas
    {
        return $this->atsiliepimas;
    }

    public function setAtsiliepimas(?Atsiliepimas $atsiliepimas): self
    {
        $this->atsiliepimas = $atsiliepimas;

        // set (or unset) the owning side of the relation if necessary
        $newUzsakymas = null === $atsiliepimas ? null : $this;
        if ($atsiliepimas->getUzsakymas() !== $newUzsakymas) {
            $atsiliepimas->setUzsakymas($newUzsakymas);
        }

        return $this;
    }
}

src/Form/UzsakymasType.php
<?php

namespace App\Form;

use App\Entity\Uzsakymas;
use App\Form\SiuntinysType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UzsakymasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pristatymo_data')
            ->add('adresas')
            ->add('siuntinys', SiuntinysType::class)
        ;

        if($options['showUser']) {
            $builder->add('user');
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Uzsakymas::class,
            'showUser' => null,
        ]);
    }
}

src/Controller/UzsakymasController.php
<?php

namespace App\Controller;

use App\Entity\Atsiliepimas;
use App\Entity\Uzsakymas;
use App\Entity\UzsakymoBusena;
use App\Form\AtsiliepimasType;
use App\Form\UzsakymasType;
use App\Repository\UzsakymasRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/uzsakymas")
 */
class UzsakymasController extends AbstractController
{
    /**
     * @Route("/", name="uzsakymas_index", methods={"GET"})
     */
    public function index(UzsakymasRepository $uzsakymasRepository): Response
    {
        $user = $this->getUser();
        $uzsakymai = null;
        if ($user->getUserType()->getName() == 'Admin') {
            $uzsakymai = $uzsakymasRepository->findAll();
        } else {
            $uzsakymai = $uzsakymasRepository->findByUser($user->getId());
        }
        return $this->render('uzsakymas/index.html.twig', [
            'uzsakymas' => $uzsakymai,
            'controller_name' => 'Užsakymų sąrašas',
        ]);
    }

    /**
     * @Route("/new", name="uzsakymas_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $uzsakymas = new Uzsakymas();
        $user = $this->getUser();
        $form = $this->createForm(UzsakymasType::class, $uzsakymas);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tipas = $this->getDoctrine()->getRepository(UzsakymoBusena::class)->findOneBySomeField('Vykdomas');
            $uzsakymas->setBusena($tipas);
            $uzsakymas->setUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($uzsakymas);
            $entityManager->flush();

            return $this->redirectToRoute('uzsakymas_index');
        }

        return $this->render('uzsakymas/new.html.twig', [
            'uzsakyma' => $uzsakymas,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="uzsakymas_show", methods={"GET", "POST"})
     */
    public function show(Request $request, Uzsakymas $uzsakyma): Response
    {
        $user = $this->getUser();
        if ($user->getUserType()->getName() != 'Admin' && $uzsakyma->getUser()->getId() != $user->getId()) {
            return $this->redirectToRoute('uzsakymas_index');
        }
        $atsiliepima = null;
        $formView = null;
        if (!$uzsakyma->getAtsiliepimas()) {
            $atsiliepima = new Atsiliepimas();
            $form = $this->createForm(AtsiliepimasType::class, $atsiliepima);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $atsiliepima->setUser($user);
                $atsiliepima->setUzsakymas($uzsakyma);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($atsiliepima);
                $entityManager->flush();

                $this->addFlash('success', 'Atsiliepimas sėkmingai parašytas');

                return $this->redirectToRoute('uzsakymas_show', array('id' => $uzsakyma->getId()));
            }

            $formView = $form->createView();
        }
        return $this->render('uzsakymas/show.html.twig', [
            'uzsakyma' => $uzsakyma,
            'atsiliepima' => $atsiliepima,
            'form' => $formView,
            'edit' => false,
        ]);
    }

    /**
     * @Route("/show/{id}/edit", name="uzsakymas_show_edit", methods={"GET", "POST"})
     */
    public function show_edit(Request $request, Uzsakymas $uzsakyma): Response
    {
        if(!$uzsakyma->getAtsiliepimas()) {
            return $this->redirectToRoute('uzsakymas_show', array('id' => $uzsakyma->getId()));
        }
        $user = $this->getUser();
        if ($user->getUserType()->getName() != 'Admin' && $uzsakyma->getUser()->getId() != $user->getId()) {
            return $this->redirectToRoute('uzsakymas_index');
        }
        $atsiliepima = null;
        $formView = null;
        if ($uzsakyma->getAtsiliepimas()) {
            $form = $this->createForm(AtsiliepimasType::class, $uzsakyma->getAtsiliepimas());
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->flush();

                $this->addFlash('success', 'Atsiliepimas sėkmingai atnaujintas');

                return $this->redirectToRoute('uzsakymas_show', array('id' => $uzsakyma->getId()));
            }

            $formView = $form->createView();
        }
        return $this->render('uzsakymas/show.html.twig', [
            'uzsakyma' => $uzsakyma,
            'atsiliepima' => $atsiliepima,
            'form' => $formView,
            'edit' => true,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="uzsakymas_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Uzsakymas $uzsakymas): Response
    {
        $user = $this->getUser();
        if ($user->getUserType()->getName() != 'Admin' && $uzsakymas->getUser()->getId() != $user->getId()) {
            return $this->redirectToRoute('uzsakymas_index');
        }
        $showUserForm = null;
        if ($user->getUserType()->getName() == 'Admin') {
            $showUserForm = true;
        }
        $form = $this->createForm(UzsakymasType::class, $uzsakymas, array('showUser' => $showUserForm));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($uzsakymas->getBusena()->getPavadinimas() === "Patvirtintas") {
                $this->addFlash('error', 'Užsakymo redaguoti negalite, nes jis jau yra patvirtintas');
            } else {
                /* $busena = $form->get('busena')->getData();
                if($busena == 'Patvirtintas') {
                    $uzsakymas->setPatvirtinimoData(new DateTime());
                } */
                $this->addFlash('success', 'Užsakymas sėkmingai atnaujintas');
                $this->getDoctrine()->getManager()->flush();
            }

            return $this->redirectToRoute('uzsakymas_index');
        }

        return $this->render('uzsakymas/edit.html.twig', [
            'uzsakyma' => $uzsakymas,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="uzsakymas_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN", statusCode=404, message="Neturite tokių teisių")
     */
    public function delete(Request $request, Uzsakymas $uzsakyma): Response
    {
        if ($this->isCsrfTokenValid('delete' . $uzsakyma->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($uzsakyma);
            $entityManager->flush();
        }

        return $this->redirectToRoute('uzsakymas_index');
    }

    /**
     * @Route("/patvirtinti/{id}", name="uzsakymas_approve", methods={"POST"})
     * @IsGranted("ROLE_ADMIN", statusCode=404, message="Neturite tokių teisių")
     */
    public function approve(Request $request, Uzsakymas $uzsakyma): Response
    {
        if ($this->isCsrfTokenValid('approve' . $uzsakyma->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $tipas = $this->getDoctrine()->getRepository(UzsakymoBusena::class)->findOneBySomeField('Patvirtintas');
            $uzsakyma->setBusena($tipas);
            $uzsakyma->setPatvirtinimoData(new DateTime());
            $entityManager->flush();
        }

        return $this->redirectToRoute('uzsakymas_index');
    }

    /**
     * @Route("/atmesti/{id}", name="uzsakymas_deny", methods={"POST"})
     * @IsGranted("ROLE_ADMIN", statusCode=404, message="Neturite tokių teisių")
     */
    public function deny(Request $request, Uzsakymas $uzsakyma): Response
    {
        if ($this->isCsrfTokenValid('deny' . $uzsakyma->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $tipas = $this->getDoctrine()->getRepository(UzsakymoBusena::class)->findOneBySomeField('Atmestas');
            $uzsakyma->setBusena($tipas);
            $entityManager->flush();
        }

        return $this->redirectToRoute('uzsakymas_index');
    }

    /**
     * @Route("/nepatvirtinti", name="uzsakymas_waiting", methods={"GET"})
     */
    public function waiting_list(UzsakymasRepository $uzsakymasRepository): Response
    {
        $tipas = $this->getDoctrine()->getRepository(UzsakymoBusena::class)->findOneBySomeField('Vykdomas');
        $user = $this->getUser();
        $uzsakymai = null;
        if ($user->getUserType()->getName() == 'Admin') {
            $uzsakymai = $uzsakymasRepository->findByBusena($tipas->getId());
        } else {
            $uzsakymai = $uzsakymasRepository->findByUserAndBusena($user->getId(), $tipas->getId());
        }
        return $this->render('uzsakymas/index.html.twig', [
            'uzsakymas' => $uzsakymai,
            'controller_name' => 'Nepatvirtinti užsakymai',
        ]);
    }
}

templates/uzsakymas/_delete_form.html.twig
{% if app.user.userType.name == 'Admin' %}
	<form method="post" action="{{ path('uzsakymas_delete', {'id': uzsakyma.id}) }}" onsubmit="return confirm('Ar tikrai norite ištrinti šį užsakymą?');">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ uzsakyma.id) }}">
		<button class="btn btn-sm btn-danger">Trinti</button>
	</form>


	{% if uzsakyma.busena.pavadinimas == 'Vykdomas' %}
		<form method="post" action="{{ path('uzsakymas_approve', {'id': uzsakyma.id}) }}">
			<input type="hidden" name="_method" value="POST">
			<input type="hidden" name="_token" value="{{ csrf_token('approve' ~ uzsakyma.id) }}">
			<button class="btn btn-sm btn-success">Patvirtinti</button>
		</form>

		<form method="post" action="{{ path('uzsakymas_deny', {'id': uzsakyma.id}) }}">
			<input type="hidden" name="_method" value="POST">
			<input type="hidden" name="_token" value="{{ csrf_token('deny' ~ uzsakyma.id) }}">
			<button class="btn btn-sm btn-warning">Atmesti</button>
		</form>
	{% endif %}
{% endif %}

templates/uzsakymas/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-primary">{{ button_label|default('Išsaugoti') }}</button>
{{ form_end(form) }}

templates/uzsakymas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Užsakymo redagavimas
{% endblock %}

{% block body %}
	<h1>Užsakymo redagavimas</h1>
	<div class="row">
		<div class="col-12 d-flex flex-row justify-content-end">
			{{ include('uzsakymas/_delete_form.html.twig') }}
			<a class="btn btn-sm btn-secondary ml-2" href="{{ path('uzsakymas_index') }}">Grįžti</a>
		</div>
	</div>
	{{ include('uzsakymas/_form.html.twig', {'button_label': 'Atnaujinti'}) }}
{% endblock %}

templates/uzsakymas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{controller_name}}{% endblock %}

{% block body %}
    <h1>{{controller_name}}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Sukurimo_data</th>
                <th>Pristatymo_data</th>
                <th>Patvirtinimo_data</th>
                <th>Klientas</th>
                <th>Adresas</th>
                <th>Būsena</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for uzsakyma in uzsakymas %}
            <tr>
                <td>{{ uzsakyma.id }}</td>
                <td>{{ uzsakyma.sukurimoData ? uzsakyma.sukurimoData|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ uzsakyma.pristatymoData ? uzsakyma.pristatymoData|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ uzsakyma.patvirtinimoData ? uzsakyma.patvirtinimoData|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ uzsakyma.user }}</td>
                <td>{{ uzsakyma.adresas }}</td>
                <td>
                    <span class="badge badge-dark">{{ uzsakyma.busena.pavadinimas }}</span>
                </td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('uzsakymas_show', {'id': uzsakyma.id}) }}">Rodyti</a>
                    {% if uzsakyma.busena.pavadinimas == 'Vykdomas' %}
                        <a class="btn btn-sm btn-secondary" href="{{ path('uzsakymas_edit', {'id': uzsakyma.id}) }}">Redaguoti</a>
                    {% else %}
                        <a class="btn btn-sm btn-secondary disabled" href="{{ path('uzsakymas_edit', {'id': uzsakyma.id}) }}">Redaguoti</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Užsakymų nerasta</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('uzsakymas_new') }}">Kurti užsakymą</a>
{% endblock %}

templates/uzsakymas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Užsakymo kūrimas{% endblock %}

{% block body %}
    <h1>Užsakymo kūrimas</h1>

    {{ include('uzsakymas/_form.html.twig') }}

    <a class="btn btn-sm btn-secondary" href="{{ path('uzsakymas_index') }}">Grįžti</a>
{% endblock %}

templates/uzsakymas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Užsakymo informacija{% endblock %}

{% block body %}
    <h1>Užsakymo informacija</h1>

    <div class="row mb-2">
        <div class="col-12 d-flex flex-row justify-content-end">
            <a class="btn btn-sm btn-primary mr-2" href="{{ path('uzsakymas_edit', {'id': uzsakyma.id}) }}">Redaguoti</a>
            <a class="btn btn-sm btn-secondary mr-2" href="{{ path('uzsakymas_index') }}">Grįžti</a>
            {{ include('uzsakymas/_delete_form.html.twig') }}
        </div>
    </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ uzsakyma.id }}</td>
            </tr>
            <tr>
                <th>Sukurimo_data</th>
                <td>{{ uzsakyma.sukurimoData ? uzsakyma.sukurimoData|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Pristatymo_data</th>
                <td>{{ uzsakyma.pristatymoData ? uzsakyma.pristatymoData|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Patvirtinimo_data</th>
                <td>{{ uzsakyma.patvirtinimoData ? uzsakyma.patvirtinimoData|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Adresas</th>
                <td>{{ uzsakyma.adresas }}</td>
            </tr>
        </tbody>
    </table>
    <h1>Atsiliepimas</h1>
    {% if form %}
        {{ include('atsiliepimas/_form.html.twig') }}
    {% else %}
        <div class="col-12 d-flex flex-row justify-content-start mb-2">
            <a class="btn btn-sm btn-primary mr-2" href="{{ path('uzsakymas_show_edit', {'id': uzsakyma.id}) }}">Redaguoti</a>
            {{ include('atsiliepimas/_delete_form.html.twig') }}
        </div>
        <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ uzsakyma.atsiliepimas.id }}</td>
            </tr>
            <tr>
                <th>Tekstas</th>
                <td>{{ uzsakyma.atsiliepimas.tekstas }}</td>
            </tr>
            <tr>
                <th>Data</th>
                <td>{{ uzsakyma.atsiliepimas.data ? uzsakyma.atsiliepimas.data|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Antraste</th>
                <td>{{ uzsakyma.atsiliepimas.antraste }}</td>
            </tr>
        </tbody>
    </table>
    {% endif %}
{% endblock %}