src/Entity/Skola.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SkolaRepository")
 */
class Skola
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tipas;

    /**
     * @ORM\Column(type="datetime")
     */
    private $isdavimo_data;

    /**
     * @ORM\Column(type="datetime")
     */
    private $grazinimo_data;

    /**
     * @ORM\Column(type="float")
     */
    private $palukanos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $isdavejas;

    /**
     * @ORM\Column(type="integer")
     */
    private $dydis;

    /**
     * @ORM\Column(type="integer")
     */
    private $grazinta_suma;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipas(): ?string
    {
        return $this->tipas;
    }

    public function setTipas(string $tipas): self
    {
        $this->tipas = $tipas;

        return $this;
    }

    public function getIsdavimoData(): ?\DateTimeInterface
    {
        return $this->isdavimo_data;
    }

    public function setIsdavimoData(\DateTimeInterface $isdavimo_data): self
    {
        $this->isdavimo_data = $isdavimo_data;

        return $this;
    }

    public function getGrazinimoData(): ?\DateTimeInterface
    {
        return $this->grazinimo_data;
    }

    public function setGrazinimoData(\DateTimeInterface $grazinimo_data): self
    {
        $this->grazinimo_data = $grazinimo_data;

        return $this;
    }

    public function getPalukanos(): ?float
    {
        return $this->palukanos;
    }

    public function setPalukanos(float $palukanos): self
    {
        $this->palukanos = $palukanos;

        return $this;
    }

    public function getIsdavejas(): ?string
    {
        return $this->isdavejas;
    }

    public function setIsdavejas(string $isdavejas): self
    {
        $this->isdavejas = $isdavejas;

        return $this;
    }

    public function getDydis(): ?int
    {
        return $this->dydis;
    }

    public function setDydis(int $dydis): self
    {
        $this->dydis = $dydis;

        return $this;
    }

    public function getGrazintaSuma(): ?int
    {
        return $this->grazinta_suma;
    }

    public function setGrazintaSuma(int $grazinta_suma): self
    {
        $this->grazinta_suma = $grazinta_suma;

        return $this;
    }
}

src/Form/SkolaType.php
<?php

namespace App\Form;

use App\Entity\Skola;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SkolaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tipas')
            ->add('isdavimo_data')
            ->add('grazinimo_data')
            ->add('palukanos')
            ->add('isdavejas')
            ->add('dydis')
            ->add('grazinta_suma')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Skola::class,
        ]);
    }
}

src/Controller/SkolaController.php
<?php

namespace App\Controller;

use App\Entity\Skola;
use App\Form\SkolaType;
use App\Repository\SkolaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/skola")
 */
class SkolaController extends AbstractController
{
    /**
     * @Route("/", name="skola_index", methods={"GET"})
     */
    public function index(SkolaRepository $skolaRepository): Response
    {
        return $this->render('skola/index.html.twig', [
            'skolas' => $skolaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="skola_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $skola = new Skola();
        $form = $this->createForm(SkolaType::class, $skola);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($skola);
            $entityManager->flush();

            return $this->redirectToRoute('skola_index');
        }

        return $this->render('skola/new.html.twig', [
            'skola' => $skola,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="skola_show", methods={"GET"})
     */
    public function show(Skola $skola): Response
    {
        return $this->render('skola/show.html.twig', [
            'skola' => $skola,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="skola_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Skola $skola): Response
    {
        $form = $this->createForm(SkolaType::class, $skola);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('skola_index');
        }

        return $this->render('skola/edit.html.twig', [
            'skola' => $skola,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="skola_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Skola $skola): Response
    {
        if ($this->isCsrfTokenValid('delete'.$skola->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($skola);
            $entityManager->flush();
        }

        return $this->redirectToRoute('skola_index');
    }
}

templates/skola/_delete_form.html.twig
<form method="post" action="{{ path('skola_delete', {'id': skola.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ skola.id) }}">
    <button class="btn">Delete</button>
</form>

templates/skola/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/skola/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Redaguoti Skolą{% endblock %}

{% block body %}
    <h1>Redaguoti Skolą</h1>

    {{ include('skola/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('skola_index') }}">back to list</a>

    {{ include('skola/_delete_form.html.twig') }}
{% endblock %}

templates/skola/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Skolos{% endblock %}

{% block body %}
    <h1>Skolos</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tipas</th>
                <th>Isdavimo_data</th>
                <th>Grazinimo_data</th>
                <th>Palukanos</th>
                <th>Isdavejas</th>
                <th>Dydis</th>
                <th>Grazinta_suma</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for skola in skolas %}
            <tr>
                <td>{{ skola.id }}</td>
                <td>{{ skola.tipas }}</td>
                <td>{{ skola.isdavimoData ? skola.isdavimoData|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ skola.grazinimoData ? skola.grazinimoData|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ skola.palukanos }}</td>
                <td>{{ skola.isdavejas }}</td>
                <td>{{ skola.dydis }}</td>
                <td>{{ skola.grazintaSuma }}</td>
                <td>
                    <a href="{{ path('skola_show', {'id': skola.id}) }}">show</a>
                    <a href="{{ path('skola_edit', {'id': skola.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('skola_new') }}">Create new</a>
{% endblock %}

templates/skola/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Užregistruoti naują skolą{% endblock %}

{% block body %}
    <h1>Sukurti naują Skolą</h1>

    {{ include('skola/_form.html.twig') }}

    <a href="{{ path('skola_index') }}">back to list</a>
{% endblock %}

templates/skola/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Skola{% endblock %}

{% block body %}
    <h1>Skola</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ skola.id }}</td>
            </tr>
            <tr>
                <th>Tipas</th>
                <td>{{ skola.tipas }}</td>
            </tr>
            <tr>
                <th>Isdavimo_data</th>
                <td>{{ skola.isdavimoData ? skola.isdavimoData|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Grazinimo_data</th>
                <td>{{ skola.grazinimoData ? skola.grazinimoData|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Palukanos</th>
                <td>{{ skola.palukanos }}</td>
            </tr>
            <tr>
                <th>Isdavejas</th>
                <td>{{ skola.isdavejas }}</td>
            </tr>
            <tr>
                <th>Dydis</th>
                <td>{{ skola.dydis }}</td>
            </tr>
            <tr>
                <th>Grazinta_suma</th>
                <td>{{ skola.grazintaSuma }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('skola_index') }}">back to list</a>

    <a href="{{ path('skola_edit', {'id': skola.id}) }}">edit</a>

    {{ include('skola/_delete_form.html.twig') }}
{% endblock %}