src/Entity/Darbuotojas.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DarbuotojasRepository")
 */
class Darbuotojas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefono_nr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $banko_saskaitos_nr;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sandelis", inversedBy="darbuotojai")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sandelis_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Zymejimasis", mappedBy="darbuotojas")
     */
    private $pasizymejimas;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $naudotojas;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DarbuotojoPareigos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pareigos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Atostogos", mappedBy="darbuotojas")
     */
    private $atostogos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Dokumentas", mappedBy="darbuotojas")
     */
    private $dokumentai;

    public function __toString(): string {
        $string = $this->getId();
        return $string;
    }

    public function __construct()
    {
        $this->pasizymejimas = new ArrayCollection();
        $this->atostogos = new ArrayCollection();
        $this->dokumentai = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTelefonoNr(): ?string
    {
        return $this->telefono_nr;
    }

    public function setTelefonoNr(string $telefono_nr): self
    {
        $this->telefono_nr = $telefono_nr;

        return $this;
    }

    public function getBankoSaskaitosNr(): ?string
    {
        return $this->banko_saskaitos_nr;
    }

    public function setBankoSaskaitosNr(string $banko_saskaitos_nr): self
    {
        $this->banko_saskaitos_nr = $banko_saskaitos_nr;

        return $this;
    }

    public function getSandelisId(): ?Sandelis
    {
        return $this->sandelis_id;
    }

    public function setSandelisId(?Sandelis $sandelis_id): self
    {
        $this->sandelis_id = $sandelis_id;

        return $this;
    }

    /**
     * @return Collection|Zymejimasis[]
     */
    public function getPasizymejimas(): Collection
    {
        return $this->pasizymejimas;
    }

    public function addPasizymejima(Zymejimasis $pasizymejima): self
    {
        if (!$this->pasizymejimas->contains($pasizymejima)) {
            $this->pasizymejimas[] = $pasizymejima;
            $pasizymejima->setDarbuotojas($this);
        }

        return $this;
    }

    public function removePasizymejima(Zymejimasis $pasizymejima): self
    {
        if ($this->pasizymejimas->contains($pasizymejima)) {
            $this->pasizymejimas->removeElement($pasizymejima);
            // set the owning side to null (unless already changed)
            if ($pasizymejima->getDarbuotojas() === $this) {
                $pasizymejima->setDarbuotojas(null);
            }
        }

        return $this;
    }


    public function getNaudotojas(): ?User
    {
        return $this->naudotojas;
    }

    public function setNaudotojas(User $naudotojas): self
    {
        $this->naudotojas = $naudotojas;

        return $this;
    }

    public function getPareigos(): ?DarbuotojoPareigos
    {
        return $this->pareigos;
    }

    public function setPareigos(?DarbuotojoPareigos $pareigos): self
    {
        $this->pareigos = $pareigos;

        return $this;
    }

    /**
     * @return Collection|Atostogos[]
     */
    public function getAtostogos(): Collection
    {
        return $this->atostogos;
    }

    public function addAtostogo(Atostogos $atostogo): self
    {
        if (!$this->atostogos->contains($atostogo)) {
            $this->atostogos[] = $atostogo;
            $atostogo->setDarbuotojas($this);
        }

        return $this;
    }

    public function removeAtostogo(Atostogos $atostogo): self
    {
        if ($this->atostogos->contains($atostogo)) {
            $this->atostogos->removeElement($atostogo);
            // set the owning side to null (unless already changed)
            if ($atostogo->getDarbuotojas() === $this) {
                $atostogo->setDarbuotojas(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Dokumentas[]
     */
    public function getDokumentai(): Collection
    {
        return $this->dokumentai;
    }

    public function addDokumentai(Dokumentas $dokumentai): self
    {
        if (!$this->dokumentai->contains($dokumentai)) {
            $this->dokumentai[] = $dokumentai;
            $dokumentai->setDarbuotojas($this);
        }

        return $this;
    }

    public function removeDokumentai(Dokumentas $dokumentai): self
    {
        if ($this->dokumentai->contains($dokumentai)) {
            $this->dokumentai->removeElement($dokumentai);
            // set the owning side to null (unless already changed)
            if ($dokumentai->getDarbuotojas() === $this) {
                $dokumentai->setDarbuotojas(null);
            }
        }

        return $this;
    }
}

src/Entity/Sandelis.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SandelisRepository")
 */
class Sandelis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pavadinimas;

    /**
     * @ORM\Column(type="string")
     */
    private $adresas;

    /**
     * @ORM\Column(type="float")
     */
    private $plotas;

    /**
     * @ORM\Column(type="integer")
     */
    private $darbuotoju_sk;

    /**
     * @ORM\Column(type="float")
     */
    private $talpa;

    /**
     * @ORM\Column(type="date")
     */
    private $statybos_metai;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Darbuotojas", mappedBy="sandelis_id")
     */
    private $darbuotojai;

    public function __construct()
    {
        $this->darbuotojai = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPavadinimas(): ?string
    {
        return $this->pavadinimas;
    }

    public function setPavadinimas(string $pavadinimas): self
    {
        $this->pavadinimas = $pavadinimas;

        return $this;
    }

    public function getAdresas(): ?string
    {
        return $this->adresas;
    }

    public function setAdresas(string $adresas): self
    {
        $this->adresas = $adresas;

        return $this;
    }

    public function getPlotas(): ?float
    {
        return $this->plotas;
    }

    public function setPlotas(float $plotas): self
    {
        $this->plotas = $plotas;

        return $this;
    }

    public function getDarbuotojuSk(): ?int
    {
        return $this->darbuotoju_sk;
    }

    public function setDarbuotojuSk(int $darbuotoju_sk): self
    {
        $this->darbuotoju_sk = $darbuotoju_sk;

        return $this;
    }

    public function getTalpa(): ?float
    {
        return $this->talpa;
    }

    public function setTalpa(float $talpa): self
    {
        $this->talpa = $talpa;

        return $this;
    }

    public function getStatybosMetai(): ?\DateTimeInterface
    {
        return $this->statybos_metai;
    }

    public function setStatybosMetai(\DateTimeInterface $statybos_metai): self
    {
        $this->statybos_metai = $statybos_metai;

        return $this;
    }

    /**
     * @return Collection|Darbuotojas[]
     */
    public function getDarbuotojai(): Collection
    {
        return $this->darbuotojai;
    }

    public function addDarbuotojai(Darbuotojas $darbuotojai): self
    {
        if (!$this->darbuotojai->contains($darbuotojai)) {
            $this->darbuotojai[] = $darbuotojai;
            $darbuotojai->setSandelisId($this);
        }

        return $this;
    }

    public function removeDarbuotojai(Darbuotojas $darbuotojai): self
    {
        if ($this->darbuotojai->contains($darbuotojai)) {
            $this->darbuotojai->removeElement($darbuotojai);
            // set the owning side to null (unless already changed)
            if ($darbuotojai->getSandelisId() === $this) {
                $darbuotojai->setSandelisId(null);
            }
        }

        return $this;
    }

    public function __toString(): string {
        return $this->getPavadinimas();
    }
}

src/Form/SandelisType.php
<?php

namespace App\Form;

use App\Entity\Sandelis;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SandelisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pavadinimas')
            ->add('adresas')
            ->add('plotas')
            ->add('darbuotoju_sk')
            ->add('talpa')
            ->add('statybos_metai')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sandelis::class,
        ]);
    }
}

src/Controller/SandelisController.php
<?php

namespace App\Controller;

use App\Entity\Sandelis;
use App\Form\SandelisType;
use App\Repository\SandelisRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/sandelis")
 */
class SandelisController extends AbstractController
{
    /**
     * @Route("/", name="sandelis_index", methods={"GET"})
     */
    public function index(SandelisRepository $sandelisRepository): Response
    {
        return $this->render('sandelis/index.html.twig', [
            'sandelis' => $sandelisRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="sandelis_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $sandeli = new Sandelis();
        $form = $this->createForm(SandelisType::class, $sandeli);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($sandeli);
            $entityManager->flush();

            return $this->redirectToRoute('sandelis_index');
        }

        return $this->render('sandelis/new.html.twig', [
            'sandeli' => $sandeli,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sandelis_show", methods={"GET"})
     */
    public function show(Sandelis $sandeli): Response
    {
        return $this->render('sandelis/show.html.twig', [
            'sandeli' => $sandeli,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="sandelis_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Sandelis $sandeli): Response
    {
        $form = $this->createForm(SandelisType::class, $sandeli);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sandelis_index');
        }

        return $this->render('sandelis/edit.html.twig', [
            'sandeli' => $sandeli,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sandelis_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Sandelis $sandeli): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sandeli->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($sandeli);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sandelis_index');
    }
}

templates/sandelis/_delete_form.html.twig
<form method="post" action="{{ path('sandelis_delete', {'id': sandeli.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sandeli.id) }}">
    <button class="btn btn-sm btn-danger" class="btn">Ištrinti</button>
</form>

templates/sandelis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Išsaugoti įrašą') }}</button>
{{ form_end(form) }}

templates/sandelis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Sandelis{% endblock %}

{% block body %}
    <h1>Edit Sandelis</h1>

    {{ include('sandelis/_form.html.twig', {'button_label': 'Atnaujinti'}) }}

    <a class="btn btn-success" href="{{ path('sandelis_index') }}">Atgal į sąrašą</a>

    {{ include('sandelis/_delete_form.html.twig') }}
{% endblock %}

templates/sandelis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sandelis index{% endblock %}

{% block body %}
    <h1>Kompanijos Sandeliai</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pavadinimas</th>
                <th>Adresas</th>
                <th>Plotas</th>
                <th>Darbuotojų skaičius</th>
                <th>Talpa</th>
                <th>Statybos metai</th>
                <th>Veiksmai</th>
            </tr>
        </thead>
        <tbody>
        {% for sandeli in sandelis %}
            <tr>
                <td>{{ sandeli.id }}</td>
                <td>{{ sandeli.pavadinimas }}</td>
                <td>{{ sandeli.adresas }}</td>
                <td>{{ sandeli.plotas }}</td>
                <td>{{ sandeli.darbuotojuSk }}</td>
                <td>{{ sandeli.talpa }}</td>
                <td>{{ sandeli.statybosMetai ? sandeli.statybosMetai|date('Y-m-d') : '' }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('sandelis_show', {'id': sandeli.id}) }}">Detaliai</a>
                    <a class="btn btn-sm btn-secondary" href="{{ path('sandelis_edit', {'id': sandeli.id}) }}">Redaguoti</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Nėra sandėlių duomenų bazėje</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('sandelis_new') }}">Pridėti naują</a>
{% endblock %}

templates/sandelis/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Sandelis{% endblock %}

{% block body %}
    <h1>Kurti naują sandėlį</h1>

    {{ include('sandelis/_form.html.twig') }}

    <a class="btn btn-success" href="{{ path('sandelis_index') }}">Atgal į sąrašą</a>
{% endblock %}

templates/sandelis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sandėlis{% endblock %}

{% block body %}
    <h1>Sandėlis</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sandeli.id }}</td>
            </tr>
            <tr>
                <th>Pavadinimas</th>
                <td>{{ sandeli.pavadinimas }}</td>
            </tr>
            <tr>
                <th>Adresas</th>
                <td>{{ sandeli.adresas }}</td>
            </tr>
            <tr>
                <th>Plotas</th>
                <td>{{ sandeli.plotas }}</td>
            </tr>
            <tr>
                <th>Darbuotojų skaičius</th>
                <td>{{ sandeli.darbuotojuSk }}</td>
            </tr>
            <tr>
                <th>Talpa</th>
                <td>{{ sandeli.talpa }}</td>
            </tr>
            <tr>
                <th>Statybos metai</th>
                <td>{{ sandeli.statybosMetai ? sandeli.statybosMetai|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-success" class="btn btn-success" href="{{ path('sandelis_index') }}">Atgal į sąrašą</a>
 
    <a class="btn btn-sm btn-secondary" href="{{ path('sandelis_edit', {'id': sandeli.id}) }}">Redaguoti</a>

    {{ include('sandelis/_delete_form.html.twig') }}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pareigos</th>
                <th>Telefono nr</th>
                <th>Banko sąskaitos nr</th>
                <th>Veiksmai</th>
            </tr>
        </thead>
        <tbody>
        {% for darbuotoja in sandeli.darbuotojai%}
            <tr>
                <td>{{ darbuotoja.id }}</td>
                <td>{{ darbuotoja.pareigos }}</td>
                <td>{{ darbuotoja.telefonoNr }}</td>
                <td>{{ darbuotoja.bankoSaskaitosNr }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('darbuotojas_show', {'id': darbuotoja.id}) }}">Detaliau</a>
                    {# <a href="{{ path('darbuotojas_edit', {'id': darbuotoja.id}) }}">Redaguoti</a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Nėra dirbančių darbuotojų</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}