src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\UserType", inversedBy="users")
     */
    private $userType;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vardas;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pavarde;

    /**
     * @ORM\Column(type="date")
     */
    private $gimimo_data;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pasto_kodas;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresas;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Uzsakymas", mappedBy="user")
     */
    private $uzsakymai;

    /** 
     * @ORM\OneToMany(targetEntity="App\Entity\Apmokejimas", mappedBy="Kliento_id")
     */
    private $kliento_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Atsiliepimas", mappedBy="user")
     */
    private $atsiliepimai;

    public function __construct()
    {
        $this->uzsakymai = new ArrayCollection();
        $this->kliento_id = new ArrayCollection();
        $this->atsiliepimai = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return $this->getUserType()->getRoles();
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserType(): ?UserType
    {
        return $this->userType;
    }

    public function setUserType(?UserType $userType): self
    {
        $this->userType = $userType;

        return $this;
    }

    public function getVardas(): ?string
    {
        return $this->vardas;
    }

    public function setVardas(string $vardas): self
    {
        $this->vardas = $vardas;

        return $this;
    }

    public function getPavarde(): ?string
    {
        return $this->pavarde;
    }

    public function setPavarde(string $pavarde): self
    {
        $this->pavarde = $pavarde;

        return $this;
    }

    public function getGimimoData(): ?\DateTimeInterface
    {
        return $this->gimimo_data;
    }

    public function setGimimoData(\DateTimeInterface $gimimo_data): self
    {
        $this->gimimo_data = $gimimo_data;

        return $this;
    }

    public function getPastoKodas(): ?string
    {
        return $this->pasto_kodas;
    }

    public function setPastoKodas(string $pasto_kodas): self
    {
        $this->pasto_kodas = $pasto_kodas;

        return $this;
    }

    public function getAdresas(): ?string
    {
        return $this->adresas;
    }

    public function setAdresas(string $adresas): self
    {
        $this->adresas = $adresas;

        return $this;
    }

    /**
     * @return Collection|Uzsakymas[]
     */
    public function getUzsakymai(): Collection
    {
        return $this->uzsakymai;
    }

    public function addUzsakyma(Uzsakymas $uzsakymas): self
    {
        if (!$this->uzsakymai->contains($uzsakymas)) {
            $this->uzsakymai[] = $uzsakymas;
            $uzsakymas->setUser($this);
        }

        return $this;
    }

    public function removeUzsakymas(Uzsakymas $uzsakymas): self
    {
        if ($this->uzsakymai->contains($uzsakymas)) {
            $this->uzsakymai->removeElement($uzsakymas);
            // set the owning side to null (unless already changed)
            if ($uzsakymas->getUser() === $this) {
                $uzsakymas->setUser(null);
            }
        }

        return $this;
    }

    public function __toString(): string {
        $string = $this->getVardas() . " " . $this->getPavarde();
        return $string;
    }

    /**
     * @return Collection|Apmokejimas[]
     */
    public function getKlientoId(): Collection
    {
        return $this->kliento_id;
    }

    public function addKlientoId(Apmokejimas $klientoId): self
    {
        if (!$this->kliento_id->contains($klientoId)) {
            $this->kliento_id[] = $klientoId;
            $klientoId->setKlientoId($this);
        }

        return $this;
    }

    public function removeKlientoId(Apmokejimas $klientoId): self
    {
        if ($this->kliento_id->contains($klientoId)) {
            $this->kliento_id->removeElement($klientoId);
            // set the owning side to null (unless already changed)
            if ($klientoId->getKlientoId() === $this) {
                $klientoId->setKlientoId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Atsiliepimas[]
     */
    public function getAtsiliepimas(): Collection
    {
        return $this->atsiliepimas;
    }

    public function addAtsiliepimas(Atsiliepimas $atsiliepimas): self
    {
        if (!$this->atsiliepimas->contains($atsiliepimas)) {
            $this->atsiliepimas[] = $atsiliepimas;
            $atsiliepimas->setUser($this);
        }

        return $this;
    }

    public function removeAtsiliepimas(Atsiliepimas $atsiliepimas): self
    {
        if ($this->atsiliepimas->contains($atsiliepimas)) {
            $this->atsiliepimas->removeElement($atsiliepimas);
            // set the owning side to null (unless already changed)
            if ($atsiliepimas->getUser() === $this) {
                $atsiliepimas->setUser(null);
            }
        }

        return $this;
    }
}

src/Entity/UserType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserTypeRepository")
 */
class UserType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="userType")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setUserType($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getUserType() === $this) {
                $user->setUserType(null);
            }
        }

        return $this;
    }

    public function __toString(): string {
        return $this->getName();
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('vardas')
            ->add('pavarde')
            ->add('gimimo_data', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('pasto_kodas')
            ->add('adresas')
        ;

        if($options['showBusena']) {
            $builder
                ->add('userType');
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'showBusena' => null,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        $appUser = $this->getUser();
        if($appUser->getUserType()->getName() != 'Admin') {
            return $this->redirectToRoute('user_show', array('id' => $appUser->getId()));
        }
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN", statusCode=404, message="Neturite tokių teisių")
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        $appUser = $this->getUser();
        if($appUser->getUserType()->getName() != 'Admin' && $user->getId() != $appUser->getId()) {
            return $this->redirectToRoute('user_show', array('id' => $appUser->getId()));
        }
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $appUser = $this->getUser();
        if($appUser->getUserType()->getName() != 'Admin' && $user->getId() != $appUser->getId()) {
            return $this->redirectToRoute('user_edit', array('id' => $user->getId()));
        }
        $showBusena = null;
        if($appUser->getUserType()->getName() == 'Admin') {
            $showBusena = true;
        }

        $form = $this->createForm(UserType::class, $user, array('showBusena' => $showBusena));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN", statusCode=404, message="Neturite tokių teisių")
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
{% if app.user.userType.name == 'Admin' %}
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Ar tikrai norite ištrinti šį vartotoją?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-sm btn-danger">Trinti</button>
</form>
{% endif %}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-primary">{{ button_label|default('Išsaugoti') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Redaguoti vartotoją{% endblock %}

{% block body %}
    <h1>Redaguoti vartotoją</h1>
    <div class="row">
        <div class="col-12 d-flex flex-row justify-content-end">
            {{ include('user/_delete_form.html.twig') }}
            {% if app.user.userType.name == 'Admin' %}
            <a class="btn btn-sm btn-secondary ml-2" href="{{ path('user_index') }}">Grįžti</a>
            {% endif %}
        </div>
    </div>

    {{ include('user/_form.html.twig', {'button_label': 'Atnaujinti'}) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vartotojų valdymas{% endblock %}

{% block body %}
    <h1>Vartotojų sąrašas</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Vardas</th>
                <th>Pavarde</th>
                <th>Gimimo_data</th>
                <th>Pasto_kodas</th>
                <th>Adresas</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.vardas }}</td>
                <td>{{ user.pavarde }}</td>
                <td>{{ user.gimimoData ? user.gimimoData|date('Y-m-d') : '' }}</td>
                <td>{{ user.pastoKodas }}</td>
                <td>{{ user.adresas }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('user_show', {'id': user.id}) }}">Rodyti</a>
                    <a class="btn btn-sm btn-secondary" href="{{ path('user_edit', {'id': user.id}) }}">Redaguoti</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Vartotojų nerasta</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('user_new') }}">Kurti naują vartotoją</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Naujas vartotojas{% endblock %}

{% block body %}
    <h1>Kurti naują vartotoją</h1>

    {{ include('user/_form.html.twig') }}
    {% if app.user.userType.name == 'Admin' %}
        <a class="btn btn-sm btn-secondary" href="{{ path('user_index') }}">Grįžti</a>
    {% endif %}
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{user.vardas}} {{user.pavarde}}{% endblock %}

{% block body %}
    <h1>{{user.vardas}} {{user.pavarde}}</h1>

    <div class="row mb-2">
        <div class="col-12 d-flex flex-row justify-content-end">
            <a class="btn btn-sm btn-primary mr-2" href="{{ path('user_edit', {'id': user.id}) }}">Redaguoti</a>
            {% if app.user.userType.name == 'Admin' %}
                <a class="btn btn-sm btn-secondary mr-2" href="{{ path('user_index') }}">Grįžti</a>
            {% endif %}
            {{ include('user/_delete_form.html.twig') }}
        </div>
    </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Vardas</th>
                <td>{{ user.vardas }}</td>
            </tr>
            <tr>
                <th>Pavarde</th>
                <td>{{ user.pavarde }}</td>
            </tr>
            <tr>
                <th>Gimimo_data</th>
                <td>{{ user.gimimoData ? user.gimimoData|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Pasto_kodas</th>
                <td>{{ user.pastoKodas }}</td>
            </tr>
            <tr>
                <th>Adresas</th>
                <td>{{ user.adresas }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}